//for matrix
export enum MatrixPosition {
  TOP_LEFT = "TOP_LEFT",
  TOP_RIGHT = "TOP_RIGHT",
  BOTTOM_LEFT = "BOTTOM_LEFT",
  BOTTOM_RIGHT = "BOTTOM_RIGHT",
  CENTER = "CENTER",
  BOTTOM_CENTER = "BOTTOM_CENTER",
  TOP_CENTER = "TOP_CENTER",
  LEFT_CENTER = "LEFT_CENTER",
  RIGHT_CENTER = "RIGHT_CENTER",
}
